import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: record } = trpc.useQuery([
    "record.findAll",
  ]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {record?.map((r) => (
          <div key={r.id}>
            {r.match?.number} - {r.team?.name}
          </div>
        ))}
      </main>
    </>
  );
};

export default Home;
