import { scoringCardFactory } from '~/components/input/ScoringCard';
import {
  objectiveAutoDefaultSchema,
  objectiveAutoKeys,
  objectiveAutoSchema,
  objectiveEndgameDefaultSchema,
  objectiveEndgameKeys,
  objectiveEndgameSchema,
  objectiveInfoDefaultSchema,
  objectiveInfoKeys,
  objectiveInfoSchema,
  objectiveOtherDefaultSchema,
  objectiveOtherKeys,
  objectiveOtherSchema,
  objectivePostgameDefaultSchema,
  objectivePostgameKeys,
  objectivePostgameSchema,
  objectivePregameDefaultSchema,
  objectivePregameKeys,
  objectivePregameSchema,
  objectiveTeleopDefaultSchema,
  objectiveTeleopKeys,
  objectiveTeleopSchema,
  pitAutoDefaultSchema,
  pitAutoKeys,
  pitAutoSchema,
  pitDriveDefaultSchema,
  pitDriveKeys,
  pitDriveSchema,
  pitEndgameDefaultSchema,
  pitEndgameKeys,
  pitEndgameSchema,
  pitInfoDefaultSchema,
  pitInfoKeys,
  pitInfoSchema,
  pitOtherDefaultSchema,
  pitOtherKeys,
  pitOtherSchema,
  pitSpecificationsDefaultSchema,
  pitSpecificationsKeys,
  pitSpecificationsSchema,
  pitTeleopDefaultSchema,
  pitTeleopKeys,
  pitTeleopSchema,
} from '~/models';
import {
  objectiveAutoAtom,
  objectiveEndgameAtom,
  objectiveInfoAtom,
  objectiveOtherAtom,
  objectivePostgameAtom,
  objectivePregameAtom,
  objectiveTeleopAtom,
  pitAutoAtom,
  pitDriveAtom,
  pitEndgameAtom,
  pitInfoAtom,
  pitOtherAtom,
  pitSpecificationsAtom,
  pitTeleopAtom,
} from '~/state';

export const scoringCards: ReturnType<typeof scoringCardFactory>[] = [
  // Objective
  scoringCardFactory({
    currentPage: 'ObjectiveInfo',
    screen: 'ObjectiveInfo',
    atom: objectiveInfoAtom,
    keys: objectiveInfoKeys,
    zodSchema: objectiveInfoSchema,
    defaults: objectiveInfoDefaultSchema,
    type: { name: 'objective' },
    nextPage: 'ObjectivePregame',
  }),

  scoringCardFactory({
    currentPage: 'ObjectivePregame',
    screen: 'ObjectivePregame',
    atom: objectivePregameAtom,
    keys: objectivePregameKeys,
    zodSchema: objectivePregameSchema,
    defaults: objectivePregameDefaultSchema,
    type: { name: 'objective' },
    nextPage: 'ObjectiveAuto',
  }),

  scoringCardFactory({
    currentPage: 'ObjectiveAuto',
    screen: 'ObjectiveAuto',
    atom: objectiveAutoAtom,
    keys: objectiveAutoKeys,
    zodSchema: objectiveAutoSchema,
    defaults: objectiveAutoDefaultSchema,
    type: { name: 'objective' },
    nextPage: 'ObjectiveTeleop',
  }),

  scoringCardFactory({
    currentPage: 'ObjectiveTeleop',
    screen: 'ObjectiveTeleop',
    atom: objectiveTeleopAtom,
    keys: objectiveTeleopKeys,
    zodSchema: objectiveTeleopSchema,
    defaults: objectiveTeleopDefaultSchema,
    type: { name: 'objective' },
    nextPage: 'ObjectiveEndgame',
  }),

  scoringCardFactory({
    currentPage: 'ObjectiveEndgame',
    screen: 'ObjectiveEndgame',
    atom: objectiveEndgameAtom,
    keys: objectiveEndgameKeys,
    zodSchema: objectiveEndgameSchema,
    defaults: objectiveEndgameDefaultSchema,
    type: { name: 'objective' },
    nextPage: 'ObjectivePostgame',
  }),

  scoringCardFactory({
    currentPage: 'ObjectivePostgame',
    screen: 'ObjectivePostgame',
    atom: objectivePostgameAtom,
    keys: objectivePostgameKeys,
    zodSchema: objectivePostgameSchema,
    defaults: objectivePostgameDefaultSchema,
    type: { name: 'objective' },
    nextPage: 'ObjectiveOther',
  }),

  scoringCardFactory({
    currentPage: 'ObjectiveOther',
    screen: 'ObjectiveOther',
    atom: objectiveOtherAtom,
    keys: objectiveOtherKeys,
    zodSchema: objectiveOtherSchema,
    defaults: objectiveOtherDefaultSchema,
    type: { name: 'objective' },
    nextPage: 'QR',
  }),

  // Pit
  scoringCardFactory({
    currentPage: 'PitInfo',
    screen: 'PitInfo',
    atom: pitInfoAtom,
    keys: pitInfoKeys,
    zodSchema: pitInfoSchema,
    defaults: pitInfoDefaultSchema,
    type: { name: 'pit' },
    nextPage: 'PitSpecifications',
  }),

  scoringCardFactory({
    currentPage: 'PitSpecifications',
    screen: 'PitSpecifications',
    atom: pitSpecificationsAtom,
    keys: pitSpecificationsKeys,
    zodSchema: pitSpecificationsSchema,
    defaults: pitSpecificationsDefaultSchema,
    type: { name: 'pit' },
    nextPage: 'PitDrive',
  }),

  scoringCardFactory({
    currentPage: 'PitDrive',
    screen: 'PitDrive',
    atom: pitDriveAtom,
    keys: pitDriveKeys,
    zodSchema: pitDriveSchema,
    defaults: pitDriveDefaultSchema,
    type: { name: 'pit' },
    nextPage: 'PitAuto',
  }),

  scoringCardFactory({
    currentPage: 'PitAuto',
    screen: 'PitAuto',
    atom: pitAutoAtom,
    keys: pitAutoKeys,
    zodSchema: pitAutoSchema,
    defaults: pitAutoDefaultSchema,
    type: { name: 'pit' },
    nextPage: 'PitTeleop',
  }),

  scoringCardFactory({
    currentPage: 'PitTeleop',
    screen: 'PitTeleop',
    atom: pitTeleopAtom,
    keys: pitTeleopKeys,
    zodSchema: pitTeleopSchema,
    defaults: pitTeleopDefaultSchema,
    type: { name: 'pit' },
    nextPage: 'PitEndgame',
  }),

  scoringCardFactory({
    currentPage: 'PitEndgame',
    screen: 'PitEndgame',
    atom: pitEndgameAtom,
    keys: pitEndgameKeys,
    zodSchema: pitEndgameSchema,
    defaults: pitEndgameDefaultSchema,
    type: { name: 'pit' },
    nextPage: 'PitOther',
  }),

  scoringCardFactory({
    currentPage: 'PitOther',
    screen: 'PitOther',
    atom: pitOtherAtom,
    keys: pitOtherKeys,
    zodSchema: pitOtherSchema,
    defaults: pitOtherDefaultSchema,
    type: { name: 'pit' },
    nextPage: 'QR',
  }),
];
